config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :users
  root "home#home_page"
  get "about", to: "about#about_page"
  get "login", to: "session#new"
  post "login", to: "session#create"
  get "logout", to: "session#destroy"
  delete "logout", to: "session#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  has_many :trips, dependent: :destroy
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :userName, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about_page
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You have to be logged in to perform the action"
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def initialize
    super
    employee = Employee.new
    employee.set_name('Learning Ruby on Rails')
    p employee.get_name
  end
  def home_page
  end
end
# Learning Ruby on Rails
class Person
  def set_name(name)
    @name = name
  end
end
class Person
  def get_name
    @name
  end
end
class Employee
  delegate :set_name, :get_name, to: :@person
  def initialize
    @person = Person.new
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You are successfully authenticated"
      redirect_to user
    else
      flash.now[:error] = "Wrong email or password"
      render action: 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]
  before_action :require_user
  # GET /trips or /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1 or /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = Trip.new(trip_params)
    # TODO: temporary hardcoded, implement Auth and remove temp code for assoc User
    @trip.user = current_user
    respond_to do |format|
      if @trip.save
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:title, :description, :start_time, :end_time, :duration)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  # before_action :require_user, except: [ :new ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:firstName, :lastName, :userName, :email, :phone, :location, :position, :password)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/about_page.html.erb
<h1>This is About page</h1>

app/views/home/home_page.html.erb
<h1>This is travellers app</h1>
<%= link_to "Sign up", new_user_path %>
<%= link_to "Login", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Companion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/_form.html.erb
<% flash.each do | type, msg | %>
  <div style="color: lightpink; margin: 10px;">
    <%= msg %>
  </div>
<% end %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(scope: :session, url: login_path, local: true) do | form |  %>
        <%= form.label :email %>
        <div class="col-10">
          <%= form.email_field :email, placeholder: "Enter your email" %>
        </div>

        <%= form.label :password %>
        <div class="col-10">
          <%= form.password_field :password, placeholder: "Enter your password" %>
        </div>

        <%= form.submit "Login", style: "margin: 10px; width: 100px;" %>
      <% end %>
    </div>
  </div>
</div>

app/views/session/new.html.erb
<h1>Login:</h1>
<%= render 'form' %>

app/views/trips/_form.html.erb
<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<div id="<%= dom_id trip %>">
  <p>
    <strong>Title:</strong>
    <%= trip.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= trip.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= trip.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= trip.end_time %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= trip.duration %>
  </p>

</div>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>
<h2><%= @trip.user.firstName %>'s trip</h2>
<% if logged_in? && @trip.user == current_user %>
  <%= render "form", trip: @trip %>
<% end %>

<br>

<div>
  <%= link_to "Show this trip", @trip %> |
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trips</h1>
<div id="trips">
  <% @trips.each do |trip| %>
    <% if logged_in? && trip.user == current_user %>
      <h2><%= trip.user.firstName if trip.user %>'s trip</h2>
      <%= render trip %>
      <p>
        <%= link_to "Show this trip", trip %>
      </p>
    <% end %>
  <% end %>
</div>

<%= link_to "New trip", new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trip %>

<div>
  <%= link_to "Edit this trip", edit_trip_path(@trip) %> |
  <%= link_to "Back to trips", trips_path %>

  <%= button_to "Destroy this trip", @trip, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :firstName, style: "display: block" %>
    <%= form.text_field :firstName %>
  </div>

  <div>
    <%= form.label :lastName, style: "display: block" %>
    <%= form.text_field :lastName %>
  </div>

  <div>
    <%= form.label :userName, style: "display: block" %>
    <%= form.text_field :userName %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.telephone_field :phone %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.text_field :position %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div style="margin-top: 20px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Firstname:</strong>
    <%= user.firstName %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= user.lastName %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.userName %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= user.location %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= user.position %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <% if logged_in? && user == current_user %>
      <%= render user %>
      <p>
        <%= link_to "Show this user", user %>
      </p>
    <% end %>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div style="color: white"><%= notice %></div>

<% if logged_in? %>
  <%= tag.h2 "Hello #{current_user.firstName}", style: "color: white" %>
  <!--  TODO: add logout path and delete method -->
  <%= link_to 'Logout', logout_path %>
<% end %>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>